-- ============================================================
-- FarmTech Solutions – Oracle SQL Developer
-- Fase 3 – PBL Inteligência Artificial / FIAP
--
-- Este script cria a tabela de sensores e demonstra
-- as principais consultas para análise dos dados agrícolas.
-- ============================================================


-- ────────────────────────────────────────────
-- 1. (OPCIONAL) Remover tabela anterior
-- ────────────────────────────────────────────
-- DROP TABLE SENSORES_FARMTECH;


-- ────────────────────────────────────────────
-- 2. Criar tabela
-- ────────────────────────────────────────────
CREATE TABLE SENSORES_FARMTECH (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DATA_HORA       TIMESTAMP        NOT NULL,
    UMIDADE_SOLO    NUMBER(5,1)      NOT NULL,
    FOSFORO         NUMBER(5,1)      NOT NULL,
    POTASSIO        NUMBER(5,1)      NOT NULL,
    PH              NUMBER(4,1)      NOT NULL,
    IRRIGACAO_ATIVA NUMBER(1)        DEFAULT 0 NOT NULL,
    TEMPERATURA     NUMBER(5,1)      NOT NULL,
    CHUVA_MM        NUMBER(5,1)      DEFAULT 0
);


-- ────────────────────────────────────────────
-- 3. Consulta geral (todas as leituras)
-- ────────────────────────────────────────────
SELECT * FROM SENSORES_FARMTECH
ORDER BY DATA_HORA;


-- ────────────────────────────────────────────
-- 4. Estatísticas gerais por dia
-- ────────────────────────────────────────────
SELECT
    TRUNC(DATA_HORA) AS DIA,
    ROUND(AVG(UMIDADE_SOLO), 1)  AS UMIDADE_MEDIA,
    ROUND(AVG(TEMPERATURA),  1)  AS TEMP_MEDIA,
    ROUND(AVG(PH),           1)  AS PH_MEDIO,
    SUM(CHUVA_MM)                AS CHUVA_TOTAL_MM,
    SUM(IRRIGACAO_ATIVA)         AS VEZES_IRRIGOU
FROM SENSORES_FARMTECH
GROUP BY TRUNC(DATA_HORA)
ORDER BY DIA;


-- ────────────────────────────────────────────
-- 5. Leituras que acionaram irrigação
-- ────────────────────────────────────────────
SELECT
    DATA_HORA,
    UMIDADE_SOLO,
    TEMPERATURA,
    CHUVA_MM
FROM SENSORES_FARMTECH
WHERE IRRIGACAO_ATIVA = 1
ORDER BY DATA_HORA;


-- ────────────────────────────────────────────
-- 6. Registros com umidade crítica (< 40 %)
-- ────────────────────────────────────────────
SELECT
    DATA_HORA,
    UMIDADE_SOLO,
    TEMPERATURA
FROM SENSORES_FARMTECH
WHERE UMIDADE_SOLO < 40
ORDER BY UMIDADE_SOLO ASC;


-- ────────────────────────────────────────────
-- 7. pH fora do intervalo ideal (6.0 – 6.8)
-- ────────────────────────────────────────────
SELECT
    DATA_HORA,
    PH,
    UMIDADE_SOLO
FROM SENSORES_FARMTECH
WHERE PH < 6.0 OR PH > 6.8
ORDER BY DATA_HORA;


-- ────────────────────────────────────────────
-- 8. Comparação fósforo e potássio médios
-- ────────────────────────────────────────────
SELECT
    ROUND(AVG(FOSFORO),  1) AS FOSFORO_MEDIO_PPM,
    ROUND(AVG(POTASSIO), 1) AS POTASSIO_MEDIO_PPM,
    ROUND(MIN(FOSFORO),  1) AS FOSFORO_MIN,
    ROUND(MAX(FOSFORO),  1) AS FOSFORO_MAX,
    ROUND(MIN(POTASSIO), 1) AS POTASSIO_MIN,
    ROUND(MAX(POTASSIO), 1) AS POTASSIO_MAX
FROM SENSORES_FARMTECH;


-- ────────────────────────────────────────────
-- 9. Períodos com chuva
-- ────────────────────────────────────────────
SELECT
    DATA_HORA,
    CHUVA_MM,
    UMIDADE_SOLO
FROM SENSORES_FARMTECH
WHERE CHUVA_MM > 0
ORDER BY DATA_HORA;


-- ────────────────────────────────────────────
-- 10. Total de registros
-- ────────────────────────────────────────────
SELECT COUNT(*) AS TOTAL_LEITURAS FROM SENSORES_FARMTECH;
